<?php
$pdfCollectionData = $block->getProductAttachmentCollection();
if ($pdfCollectionData->getSize() > 0) {
    foreach ($pdfCollectionData as $pdf) {
        $ext = pathinfo($pdf->getAttachmentFile(), PATHINFO_EXTENSION);
        switch ($ext) {
            case ('pdf'):
                $pdfIcon = 'pdf.png';
                break;
            case ('docx'):
            case ('doc'):
                $pdfIcon = 'doc.png';
                break;
            case ('xlsx'):
            case ('xls'):
            case ('csv'):
                $pdfIcon = 'xls.png';
                break;
            default:
                $pdfIcon = 'attachment.png';
                break;
        }
        ?>
        <a href="<?= $block->getMediaUrl() . $pdf->getAttachmentFile() ?>" target="_blank" style="display:inline-block;text-align:center;margin-right:30px">
            <img src="<?php echo $block->getViewFileUrl('Icecat_DataFeed::images/' . $pdfIcon); ?>" title ="<?= $pdf->getTitle() ?>"/>
            <span style="display: block;"><?= $pdf->getTitle() ?></span>
        </a>
    <?php } ?>
<?php } else { ?>
    <p>No Documents Available right now.</p>
<?php } ?>
